-- new schema

CREATE TABLE budget_user (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_name text,
	last_name text,
	email text,
	hashed_password text,
	create_date timestamp,
	modified_date timestamp,
	UNIQUE(email)
);

-- EAV table
CREATE TABLE user_preference_choice (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	choice_key text,
	choice_value text
);

-- generic categories 
CREATE TABLE starter_budget_category (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	display_name text NOT NULL,
	description text,
	create_date timestamp default now(),
	modified_date timestamp default now()
);

-- every user as the `starter_budget_category` values inserted into their specific `budget_category` rows
CREATE TABLE budget_category (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) default null, --nullable
	display_name text NOT NULL,
	description text,
	ignored boolean NOT NULL default FALSE,
	create_date timestamp default now(),
	modified_date timestamp default now()
);

-- entries to be associated with a category. Example - 
-- `budget_category_preassignment.description = "Digital Card Purchase - NETFLIX COM LOS GATOS CA"` should 
-- relate to `category.dislay_name = "entertainment"`.
CREATE TABLE budget_category_preassignment (
	category_id int REFERENCES budget_category(id) default null, --nullable
	description text NOT NULL, -- contains an expenditure.description
	create_date timestamp default now(),
	modified_date timestamp default now(),
	PRIMARY KEY (category_id, description)
);

-- regex input to be associated with a category.
CREATE TABLE budget_category_pattern (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	category_id int REFERENCES budget_category(id) default null, --nullable
	pattern text NOT NULL,
	create_date timestamp default now(),
	modified_date timestamp default now()
);

-- just a way to group `budget_category_limit` entries. This allows user to switch between different budget concepts.
CREATE TABLE budget_concept (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	name text NOT NULL
);

-- exists as monthly limits, but probably create 12 identitcal rows to start
CREATE TABLE budget_category_limit (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	budget_concept_id int REFERENCES budget_concept(id),
	month_id int NOT NULL,
	dollar_allotment int NOT NULL
);

-- TODO - implement this, so that double-uploads don't double-up data
-- CREATE TABLE upload_record(
-- 	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
-- 	user_id int REFERENCES budget_user(id) NOT NULL,
-- 	month int NOT NULL,
-- 	year int NOT NULL,
-- 	account_identifier text NOT NULL,
-- 	create_date timestamp default now(),
-- 	modified_date timestamp default now(),
-- 	UNIQUE (user_id, month, year, account_identifier),
-- 	CONSTRAINT account_id_check CHECK (
-- 		account_identifier = "amex" OR account_identifier = "capone"
-- 	)
-- );

-- this is how you select by month in a timestamp:
-- SELECT * FROM expenditure
-- WHERE EXTRACT(MONTH FROM date_occurred) > 10;

CREATE TABLE expenditure (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	category_id int REFERENCES budget_category(id), --nullable, expenditures start out unassigned to a category
	value decimal NOT NULL, -- -8.99
	description text NOT NULL, -- `Digital Card Purchase - NETFLIX COM LOS GATOS CA` or `CHEWY.COM`
	date_occurred timestamp NOT NULL, -- `11/02/23`
	-- upload_record REFERENCES upload_record(id), -- TODO, optional upload association, so an upload can be "un-done"
	create_date timestamp default now(),
	modified_date timestamp default now()
);

CREATE TABLE tag (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	name text NOT NULL,
	description text,
	create_date timestamp default now(),
	modified_date timestamp default now()
);

CREATE TABLE expenditure_tags_association (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	expenditure_id int REFERENCES expenditure(id) NOT NULL,
	tag_id int REFERENCES expenditure(id) NOT NULL,
	create_date timestamp default now(),
	modified_date timestamp default now()
);

-- CREATE TABLE category_labels (
-- 	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
-- 	user_id int REFERENCES budget_user(id) NOT NULL,
-- 	category_id int REFERENCES budget_category(id),
-- 	description text NOT NULL,
-- 	create_date timestamp default now(),
-- 	modified_date timestamp default now()
-- );

-- one of two columns must be non-null
-- constraint some_contraint check (not(column_a is null and column_b is null))

CREATE TABLE income_category (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	display_name text NOT NULL,
	description text NOT NULL,
	ignored boolean NOT NULL default FALSE,
	create_date timestamp default now(),
	modified_date timestamp default now()
);

CREATE TABLE income (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	category_id int REFERENCES income_category(id) NOT NULL,
	value decimal NOT NULL,
	description text NOT NULL,
	date_occurred timestamp default now(),
	create_date timestamp default now(),
	modified_date timestamp default now()
);

CREATE TABLE starter_income_category (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	display_name text NOT NULL,
	description text NOT NULL,
	create_date timestamp default now(),
	modified_date timestamp default now()
);