CREATE TABLE budget_user (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_name text, 
	last_name text,
	email text,
	hashed_password text,
	create_date timestamp,
	last_modified_date timestamp
);

-- EAV table to keep track of any user preferences
-- PLANNED -> use this to track whether user wants to allow a budget to be changeable 
-- after month has started
CREATE TABLE user_preference_choice (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	choice_key text,
	choice_value text
);

CREATE TABLE budget_ideation (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id),
	month_id int NOT NULL,
	year int NOT NULL,
	name text NOT NULL
);

-- a budget that will be referenced by budget_category_assignment & budget_category.
CREATE TABLE applied_budget (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	ideation_id int REFERENCES budget_ideation(id),
	name text
);

-- a category that will get an associated dollar value. Can exist for either a model budget or a 
-- monthly budget
CREATE TABLE budget_category (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text
);

-- a category & dollar value pair that can be assigned to either a model_budget 
-- or a monthly_budget
CREATE TABLE budget_category_assignment (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	budget_id int REFERENCES budget_ideation(id),
	budget_category_id int REFERENCES budget_category(id) NOT NULL,
	dollar_allotment int NOT NULL
);

CREATE TABLE tag (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	name text
);

CREATE TABLE expenditure (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	budget_category_assignment_id int REFERENCES budget_category_assignment(id) NOT NULL,
	value numeric NOT NULL,
	description text,
	note text,
	create_date timestamp
);

CREATE TABLE expenditure_tag (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	tag_id int REFERENCES tag(id),
	expenditure_id int REFERENCES expenditure(id) NOT NULL
);

CREATE TABLE token (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	value text,
	create_date timestamp,
	expiration_date timestamp
);