-- new schema

CREATE TABLE budget_user (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_name text, 
	last_name text,
	email text,
	hashed_password text,
	create_date timestamp,
	last_modified_date timestamp
);

-- EAV table
CREATE TABLE user_preference_choice (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	choice_key text,
	choice_value text
);

CREATE TABLE expenditure (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int REFERENCES budget_user(id) NOT NULL,
	value decimal NOT NULL, -- 8.99 as string
	description text NOT NULL, -- `Digital Card Purchase - NETFLIX COM LOS GATOS CA` or `CHEWY.COM`
	date_occurred timestamp NOT NULL, -- `11/02/23`
	create_date timestamp default now(),
	modified_date timestamp default now()
);
